### ISSUE TITLE
Events zwischen Daten herausfinden

### ISSUE THREAD

**Issue by fabianschwarzfritz** [BYE-1/Yet-Another-Calendar#11]
Bitte die wichtie Methode public List<Event> getEventBetweenDates(User user, Date from, Date til)  schnellstmögliche implementieren, damit Termine aus der Datenbank geholt werden können

**Comment by Jabro** [comment]
Hinweiß: Termine bei denen das Attribut RRULE gesetzt ist, müssen immer aus der Datenbank geholt werden (es sei denn der Beginn des Termins liegt nach dem Enddatum (Date til) des Zeitraumes, dieser Fall kann aber der Einfachkeit halber ignoriert werden und wird von mir später abgefangen.)
