### ISSUE TITLE
RDate ist eine Datelist

### ISSUE THREAD

**Issue by Jabro** [BYE-1/Yet-Another-Calendar#13]
Bei rdate (Klasse Event ) handet es sich um eine Liste von Daten, die statt dem RRULE-Attribut zur Erstellung wiederholender Termine verwendet werden kann.

DIe Datenbanktabelle muss entsprechend angepasst werden

@fabianschwarzfritz @zeller15

**Comment by soerenpottberg** [comment]
Willst du die DB-Tabelle anpassen, um direkt per SQL die mit rdate wiederholenden Termine auslesen zu können?

Falls nicht sollte eine Anpassung der Klassen Event und EventDAO reichen.

**Comment by Jabro** [comment]
ah ok, ich dachte dass muss beim Erstellen der Datenbank auch beachtet werden
