### ISSUE TITLE
Import und Export

### ISSUE THREAD

**Issue by soerenpottberg** [BYE-1/Yet-Another-Calendar#16]
Import und Export funktioniert nicht. Ich kriege beim Importieren immer noch Null-Pointer-Exceptions. Gucke bitte nach voran es liegt und leite den Issue notfalls weiter.

**Comment by Jabro** [comment]
Hi, gib mal eine genauere Beschreibung, wann die Exception Auftritt/was du machst.

**Comment by soerenpottberg** [comment]
[edit]
Der Anhang mit der Beispiel ics ging an deine E-Mail-Adresse
[/edit]

Hi,

> Hi, gib mal eine genauere Beschreibung, wann die Exception Auftritt/was  
> du machst.

Eine x-beliebige ics-Datei importieren ;-)

Sören

Am 09.07.2012, 14:56 Uhr, schrieb Jabro  
reply@reply.github.com:

> Hi, gib mal eine genauere Beschreibung, wann die Exception Auftritt/was  
> du machst.
>

**Comment by Jabro** [comment]
funktioniert, siehe Test

**Comment by Jabro** [comment]
habe den Tets auch noch einmal mit deiner Termin Datei durchlaufen lassen und das importieren funktioniert zumindest von meiner Seite aus. Der Fehler muss also bei der Datenbank oder dem TerminServlet liegen (ich konnte das bisher noch nicht nachvollziehen)
