### ISSUE TITLE
ICS ui controller

### ISSUE THREAD

**Issue by fabianschwarzfritz** [BYE-1/Yet-Another-Calendar#9]
Die Anbindung des Wrappers an die jeweiligen Controller Servlets sollen implementiert werden. Hierzu muss eine Rücksprache mit dem Frontend-Team erfolgen. Ausserdem sind (neben den in der ICS-Aufgabe realisierten Wrapper tests) auch manuelle UI tests durchzuführen.

**Comment by Jabro** [comment]
Könnte man nicht den ICS-Import direkt in die DB wegschreiben und dann einfach die momentane View komplett neu laden?
